- hosts: vms
  become: yes
  tasks:
    - name: Collect Metrics
      shell: |
        sudo apt-get update
        sudo apt-get install ca-certificates curl
        sudo install -m 0755 -d /etc/apt/keyrings
        sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        sudo chmod a+r /etc/apt/keyrings/docker.asc

        # Add the repository to Apt sources:
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
        sudo apt-get install -y  docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
        sudo systemctl enable --now docker
        sudo systemctl restart docker
    - name: Add user to Docker group
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: Restart Docker service to apply changes
      shell: |
        sudo systemctl restart docker
        docker pull seifalrahman/weather_app:latest
    - name: Cont3
      shell: |
        docker run -d -p 5000:5000 --name  WeatherAPP  seifalrahman/weather_app
        
